[build]
  command = "./netlify-build.sh"
  publish = "dist"

[build.environment]
  # Use a stable LTS version of Node.js
  NODE_VERSION = "18.19.1"
  NPM_FLAGS = "--no-optional"
  # Set memory limit to avoid memory issues during build
  NODE_OPTIONS = "--max_old_space_size=4096"

[[redirects]]
  # Handle SPA routing (for React Router)
  from = "/*"
  to = "/index.html"
  status = 200

# Specify the external modules that should be ignored during build
[functions]
  external_node_modules = ["@rollup/rollup-linux-x64-gnu"] 